### ISSUE TITLE
Highlighting custom sections with name `name`

### ISSUE THREAD

**Issue by kartva** [ardaku/app-metadata-crate#1]
As per [recommended WebAssembly](https://www.w3.org/TR/2019/REC-wasm-core-1-20191205/#name-section%E2%91%A0) and [latest WebAssembly standards](https://www.w3.org/TR/wasm-core-2/appendix/custom.html#custom-sections), the Custom Section with the name `name` is defined to be the _name section_. It consists of subsections which contain debug information consisting of names of the module, functions, locals, etc.

It might be worthwhile exposing functionality to manipulate the debug information as well, and preventing writing a custom module with the name `name` that does not conform to the specification. (That is, adding in [some more methods from parity-wasm](https://docs.rs/parity-wasm/latest/parity_wasm/elements/struct.Module.html#method.names_section).

**Comment by AldaronLau** [comment]
This sounds like a good idea!

**Comment by AldaronLau** [comment]
Name section parsing and type-checking will be supported in version 0.1.0 releasing soon, which includes necessary features (implemented on `stable`) for the pending implementation of Ardaku/Daku 1.0.0-pre.0.  Closing as complete.
