### ISSUE TITLE
Come Up With Catchy Crate Name

### ISSUE THREAD

**Issue by AldaronLau** [ardaku/app-metadata-crate#4]

**Comment by CATboardBETA** [comment]
We could go with eigenstate, which is a quantum positional state.

**Comment by AldaronLau** [comment]
Hmm, maybe.  Is there a way we can somehow cleverly connect the name to metadata?

**Comment by CATboardBETA** [comment]
Well, Eigenmeta-state directly translates to "Self meta state" (makes more sense in german), so we could use that

**Comment by AldaronLau** [comment]
Guess we're doing nucleide
